/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "msg": {
        "test": string;
        "user": {
            "register": {
                "password_different": string;
                "school_not_found": string;
                "existed": string;
                "success": string;
            };
            "login": {
                "account_not_register": string;
                "password_error": string;
                "success": string;
            };
        };
    };
};
export type I18nPath = Path<I18nTranslations>;
