/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "msg": {
        "test": string;
        "user": {
            "register": {
                "existed": string;
                "success": string;
            };
        };
    };
};
export type I18nPath = Path<I18nTranslations>;
